### ISSUE TITLE
[Bug]: mouseClicked event handler Crash

### ISSUE THREAD

**Issue by SirTwsted** [cech12/BucketLib#52] opened 2024-10-01 11:29 UTC
### Minecraft Version

v.1.21.1

### Mod Loader

NeoForge

### Mod Loader Version

v21.1.65

### Mod Version

v4.1.1.0

### Describe the Issue

Hi, 
I am using Minecraft v1.21.1 with NEOForge v21.1.65  and FTB Library v2101.1.3
I was using the FTB Quest and collecting my rewards, when BOOM got a crash when I clicked on something.  Here is the crash report.

### Crashlogs

https://paste.feed-the-beast.com/view/fa18cddf

and 

https://pastebin.com/hNd4AawF

### Steps to reproduce

Click on any rewards to get rewards, and BOOM crash.

### Anything else to note?

![bucketLIB crash](https://github.com/user-attachments/assets/95fe8192-1505-4bf7-b987-63d98d194014)

###  Response from FTB Team:
https://github.com/FTBTeam/FTB-Mods-Issues/issues/1349#issuecomment-2385038943

### Do you use any performance-enhancing mods (e.g. OptiFine)?

No, I do not use Optifine.

**Comment by cech12** [comment] 2024-10-01 16:27
Thanks for your report. I will look into that when I have time :)

**Comment by cech12** [comment] 2024-10-02 06:15
Note for me: This line causes a rebuild of CreativeTabs:

https://github.com/FTBTeam/FTB-Quests/blob/0e21d4342c5da36f353f277290f7985180466ad5/common/src/main/java/dev/ftb/mods/ftbquests/integration/item_filtering/DisplayStacksCache.java#L38C34-L38C55

I am trying to debug that, when I have the time for it.

**Comment by SirTwsted** [comment] 2024-10-02 13:07
You can give this a try.  🤷‍♀️🤔
This will change the entire class DisplayStacksCache though.

`
package dev.ftb.mods.ftbquests.integration.item_filtering;

import dev.ftb.mods.ftbquests.quest.reward.RandomReward;
import dev.ftb.mods.ftbquests.quest.task.ItemTask;
import net.minecraft.world.item.ItemStack;
import net.minecraft.world.item.CreativeModeTabs;

import java.util.*;

public class DisplayStacksCache {
	private static final Map<ItemTask, List<ItemStack>> ITEM_TASK_CACHE = new HashMap<>();
	private static final Map<RandomReward, List<ItemStack>> RANDOM_REWARD_CACHE = new HashMap<>();
	private static Collection<ItemStack> cachedSearchTabDisplayItems;

	public static List<ItemStack> get(ItemTask task) {
		return ITEM_TASK_CACHE.computeIfAbsent(task, t -> new ArrayList<>(t.getItemsToCheck()));
	}

	public static List<ItemStack> get(RandomReward reward) {
		return RANDOM_REWARD_CACHE.computeIfAbsent(reward, r -> {
			List<ItemStack> list = new ArrayList<>();
			r.table.rewards.forEach(entry -> list.addAll(entry.getDisplayItems()));
			return list;
		});
	}

	private static Collection<ItemStack> getSearchTabDisplayItems() {
		if (cachedSearchTabDisplayItems == null) {
			cachedSearchTabDisplayItems = CreativeModeTabs.searchTab().getDisplayItems();
		}
		return cachedSearchTabDisplayItems;
	}

	public static void invalidateCache() {
		ITEM_TASK_CACHE.clear();
		RANDOM_REWARD_CACHE.clear();
		cachedSearchTabDisplayItems = null;
	}

	public static List<ItemStack> getAllItems() {
		List<ItemStack> allItems = new ArrayList<>(getSearchTabDisplayItems());
		ITEM_TASK_CACHE.values().forEach(allItems::addAll);
		RANDOM_REWARD_CACHE.values().forEach(allItems::addAll);
		return allItems;
	}
}

`

Changes made:
Added a new private static field cachedSearchTabDisplayItems to store the cached result of CreativeModeTabs.searchTab().getDisplayItems().

Created a new private method getSearchTabDisplayItems() that implements the caching mechanism for the creative tab's display items.

Modified the getAllItems() method to use the new getSearchTabDisplayItems() method instead of directly calling CreativeModeTabs.searchTab().getDisplayItems().

Updated the invalidateCache() method to also clear the cachedSearchTabDisplayItems when invalidating the cache.

Changes should help improve performance by caching the result of CreativeModeTabs.searchTab().getDisplayItems(), which was potentially causing performance issues due to frequent rebuilding of CreativeTabs.



🤓

**Comment by cech12** [comment] 2024-10-02 14:36
That is not my code xD That is code of the FTB team ^^ The hint was only for me to find it faster later ^^

Your request would be worth to send to FTB as a fix and enhancement ^^

**Comment by cech12** [comment] 2024-10-03 07:06
Actually, I cannot reproduce it in my environment. I call the `CreativeModeTabs.tryRebuildTabContents` method but no crash happens with my BucketLib mod and a wooden bucket. 

@SirTwsted Do you have a modpack where I can reproduce it? Are you using other mods with fluids (which ones)? Do you have some quests for me, that you are using to reproduce it?

**Comment by SirTwsted** [comment] 2024-10-03 17:14
It's a custom mod pack I personally created that has 455 mods installed.  You need a very high-end pc to run it.
Many people can not run my personal custom mod pack, because I was forced to give it 50-GB of DDR5 RAM to run it.
And it pushes my AMD Radeon 7900-XTX a bit.  And my AMD 7950X CPU on a Gigabyte X670E Aorus Extreme motherboard.

If it happens again, I will make sure to remember, what FTB quests reward section I am in the next time.

**Comment by cech12** [comment] 2024-10-04 06:51
@SirTwsted Could you send me a list of all used mods that add fluids to the game? When you open JEI/REI you can search for "wooden bucket" and you should see all important fluids and for each can find the coresponding mod. :)
That would be awesome :)

**Comment by SirTwsted** [comment] 2024-10-04 14:26
When I type "Wooden Bucket" in JEI, for some odd reason nothing comes up anymore.
Even though I do have all the mods needed for this mod.  As shown here.

![Bucket Mods Installed](https://github.com/user-attachments/assets/3242929d-10c3-4248-ab96-e29544d8e294)


This is what I get back from JEI when looking for "Wooden Bucket".  Its very odd that it does not show up.  👀

![Nothing Shown is very odd](https://github.com/user-attachments/assets/d1ee09ef-42a2-4d2a-9710-4023a802fa58)



Anyways, I typed Liquid in the JEI search and noted down all the mods that refer to liquids anyway.  🤷‍♀️
There might be more and not showing up, but this is what I got so far.
--------------------------
Minecraft Default
Aquaculture 2
Extreme Reactors
Integrated Dynamics
Just Dire Things
Mekanism
Mekanism Generators
Mystical Aggraditions
Productive Bees
Security Craft
Sophisticated Core
The BumbleZone
Theurgy
The Undergarden
Oh The Biomes We've Gone
Industrial Foregoing
Biomes O' plenty
Ceramic Bucket
Ex Deorum
Forbidden Arcanus
Oreberries Replanted
Tank Storage
TuFuCraftReloaded



Hope this helps.  😉👍

**Comment by cech12** [comment] 2024-10-10 16:41
@SirTwsted I found the issue! It was an incompatibility with the powder snow bucket of the Forbidden Arcanus mod. It is fixed in the following upcoming versions of BucketLib:
- 1.21-4.1.1.1
- 1.20.6-3.3.1.1
- 1.20.4-3.2.2.1
- 1.20.1-2.3.5.1

Thanks again for your report and your quick answers! :)
If you find other problems, feel free to open a new issue :D

**Closed as completed by cech12** 2024-10-10 16:41 UTC
Labels: bug, mod support
