### ISSUE TITLE
[Bug]: Water logged blocks get replaced when right clicked with a custom water bucket

### ISSUE THREAD

**Issue by Janbsh** [cech12/BucketLib#41] opened 2024-06-22 04:36 UTC
### Minecraft Version

1.20.4

### Mod Loader

Quilt

### Mod Loader Version

0.26.1-beta.1

### Mod Version

1.20.4-3.2.1.0

### Describe the Issue

When you right click a water logged block with a water bucket it will replace the block with water.

**Comment by cech12** [comment] 2024-06-22 06:00
Thanks for your report. I will look into that when I have time. :)

**Comment by cech12** [comment] 2024-06-22 07:12
Thanks again for your report. The issue is fixed in the upcoming releases 1.20.4-3.2.1.1, 1.20.6-3.3.0.5 and 1.21-4.0.0.2.

**Closed as completed by cech12** 2024-06-22 07:12 UTC
Labels: bug
